---
manifests:
  - type: Package.swift
  - type: Package.resolved
  - type: Package.resolved
    path: Apps/Apps.xcworkspace/xcshareddata/swiftpm/Package.resolved
  - type: Podspec
  - type: packager
dependencies:
  - name: MapboxCoreMaps
  - name: MapboxCommon
  - name: Turf
  - name: MapboxMobileEvents
manifest_definitions:
  - name: packager
    type: SemanticVersion
    default_path: scripts/release/packager/versions.json
    command: jq -r ".$DEPSVALIDATOR_DEPENDENCY_NAME" "$DEPSVALIDATOR_MANIFEST_PATH"
